import { validationResult } from 'express-validator';
import { Request, Response, NextFunction } from 'express';

/**
 * A middleware function to extract validation results generated by express validator
 * and send them as a response if they exist.
 */
export const throwValidationErrors = (req: Request, res: Response, next: NextFunction) => {
	const result = validationResult(req).formatWith(({ msg, ...rest }) => {
		return {
			message: msg,
			...rest,
		};
	});
	if (result.isEmpty()) {
		return next();
	}
	res.status(400).json({ success: false, errors: result.array() });
};

export default throwValidationErrors;
